language: scala
scala:
- 2.10.4
script:
- du -sh ~/.ivy2
- du -s ~/.ivy2
- ls ~/.ivy2/cache
- ./sbt compile
jdk:
- oraclejdk7
env:
  matrix:
  - SBT_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1024M"
notifications:
  email:
    on_success: never
    on_failure: never
