before_install:
- sudo bash -c 'echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections'
- sudo add-apt-repository -y ppa:webupd8team/java
- sudo apt-get update
- sudo apt-get install -y oracle-java8-installer oracle-java8-set-default

script:
- echo $JAVA_HOME
- javac -version

notifications:
  email:
    on_success: never
    on_failure: never
