language: scala
scala:
- 2.10.4
cache:
  directories:
  - ~/.ivy2
script:
- du -sh ~/.ivy2
- du -s ~/.ivy2
- ls ~/.ivy2/cache
- ./sbt compile
jdk:
- oraclejdk7
notifications:
  email:
    on_success: never
    on_failure: never
